### ISSUE TITLE
Absolute content does not disappear

### ISSUE THREAD

**Issue by tim-kilian** [dimensi/vue-slide-toggle#2]
## Problem
If there is some absolute content inside the slider, then its not disappear after open is false. 

## Testcode
https://codesandbox.io/s/vue-template-f8qgh?fontsize=14
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-f8qgh?fontsize=14)

**Comment by dimensi** [comment]
@tim-kilian, thanks for the example.
I think my component should not solve such problems.
I think you can just put `position: relative` on it so that the elements with `position: absolute` do not come out of the layer flow.
I've updated your example a little bit.
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-k53y8?fontsize=14)
